-- TRIGGER PARA ACTUALIZAR LA FECHA DE ACTUALIZACIÓN DEL LIBRO
CREATE TRIGGER trg_UpdateLibroFecha
ON Libro
AFTER UPDATE
AS
BEGIN
    UPDATE Libro
    SET Actualizado_fecha = GETDATE()
    WHERE Id IN (SELECT Id FROM inserted);
END;
GO

-- TRIGGER PARA ACTUALIZAR LA FECHA DE ACTUALIZACIÓN DEL ESTUDIANTE
CREATE TRIGGER trg_UpdateEstudianteFecha
ON Estudiante
AFTER UPDATE
AS
BEGIN
    UPDATE Estudiante
    SET Actualizado_fecha = GETDATE()
    WHERE Id IN (SELECT Id FROM inserted);
END;
GO

-- TRIGGER PARA ACTUALIZAR LA FECHA DE ACTUALIZACIÓN DE LA MATERIA
CREATE TRIGGER trg_UpdateMateriaFecha
ON Materia
AFTER UPDATE
AS
BEGIN
    UPDATE Materia
    SET Actualizado_fecha = GETDATE()
    WHERE Id IN (SELECT Id FROM inserted);
END;
GO

-- TRIGGER PARA ACTUALIZAR LA FECHA DE ACTUALIZACIÓN DEL AUTOR
CREATE TRIGGER trg_UpdateAutorFecha
ON Autor
AFTER UPDATE
AS
BEGIN
    UPDATE Autor
    SET Actualizado_fecha = GETDATE()
    WHERE Id IN (SELECT Id FROM inserted);
END;
GO

-- TRIGGER PARA ACTUALIZAR LA FECHA DE ACTUALIZACIÓN DEL USUARIO
CREATE TRIGGER trg_UpdateUsuarioFecha
ON Usuario
AFTER UPDATE
AS
BEGIN
    UPDATE Usuario
    SET Actualizado_fecha = GETDATE()
    WHERE Id IN (SELECT Id FROM inserted);
END;
GO